### ISSUE TITLE
Please add a demo or screenshot/s

### ISSUE THREAD

**Issue by polyzen** [Streetwalrus/gitprompt-rs#1]

**Comment by 9ary** [comment]
I'm not sure what I could do for this. The prompt looks something like `(master↑4↓7|+2~3-5x6•8)`, where the numbers mean:
- Branch info:
  - `↑` Number of commits ahead of remote
  - `↓` Number of commits behind remote
- Work area:
  - `+` Untracked (new) files
  - `~` Modified files
  - `-` Deleted files
  - `x` Merge conflicts
- `•` Staged changes

**Comment by polyzen** [comment]
Adding that information to the readme seems sufficient.

**Comment by 9ary** [comment]
Alright. I'm also trying to add zsh detection so I'll add this while I'm at it.

**Comment by polyzen** [comment]
FWIW I've been using [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt) for some time now. Maybe its code can help.

Also, I suppose that prompt format might be a standard at this point. Do you know if this is documented somewhere?

**Comment by 9ary** [comment]
I know about zsh-git-prompt and this is loosely based on that, just a different implementation. I'm not sure how much I've diverged from it over time. I'm using the newer porcelain v2 format and I think I took some liberties with how I interpret it compared to the original. I can't even find where the Haskell version calls git.

**Comment by polyzen** [comment]
Apparently that starts here:
https://github.com/olivierverdier/zsh-git-prompt/blob/0a6c8b610e799040b612db8888945f502a2ddd9d/src/src/Utils.hs#L23

https://github.com/olivierverdier/zsh-git-prompt/commit/dae1807d6ad1c1808b9dd2b7cecab0a8350493e9#diff-f8f3412da88cd4806f23d59fe59ebc3bR54
